# Generated by Selenium IDE and modified to execute download+save actions
# Author: Thanmay Dudipati
# Date: 11/03/2024

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestRecentpdf:
    def setup_method(self, method):
        """sets up the browser options and the webdriver

        Args:
            method (method): for pytest
        """
        chrome_options = webdriver.ChromeOptions()
        prefs = {"download.default_directory": "/home/t47/Downloads/"}
        chrome_options.add_experimental_option("prefs", prefs)
        chrome_options.add_argument("--disable-extensions")
        chrome_options.add_argument("--headless")
        self.driver = webdriver.Chrome(options=chrome_options)
        self.vars = {}
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_recentpdf(self):
        """navigates to the arXiv website and downloads the most recent PDF published in a specific category and saves it to the downloads folder"""
        try:
            self.driver.get("https://arxiv.org/")
            self.driver.set_window_size(1920, 1053)
            self.driver.find_element(By.LINK_TEXT, "Advanced Search").click()
            self.driver.find_element(By.ID, "classification-computer_science").click()
            self.driver.find_element(
                By.ID, "classification-include_cross_list-1"
            ).click()
            self.driver.find_element(By.CSS_SELECTOR, ".button:nth-child(3)").click()
            dropdown = self.driver.find_element(By.ID, "order")
            dropdown.find_element(
                By.XPATH, "//option[. = 'Submission date (newest first)']"
            ).click()
            self.driver.find_element(By.LINK_TEXT, "pdf").click()
        except:
            print("Invalid URL")
